const projects = [
  {id:'rag', number:'01', category:'IA GÉNÉRATIVE · RAG', title:'Retrouver l’information.\nConstruire une réponse.', intro:'Un système RAG pour faciliter la recherche dans une base documentaire interne.', tags:['LangChain','Mistral','BGE-M3','FAISS'], problem:'Faciliter l’accès à l’information répartie entre des demandes / réponses historiques et la documentation métier.', work:'Structuration de deux bases de connaissances, recherche sémantique avec les embeddings BGE-M3, indexation FAISS et conception du prompt de réponse.', scope:'Projet réalisé à la Caisse des Dépôts. Présentation du principe général ; documents et code internes non publiés.'},
  {id:'classification', number:'02', category:'MACHINE LEARNING · NLP', title:'Donner une direction\nà chaque courrier.', intro:'Maintenance et évolution d’un pipeline de classification multiclasse de courriers administratifs.', tags:['Scikit-learn','TF-IDF','SVM','Dataiku'], problem:'Adapter la classification à l’évolution des données et à l’ajout de nouvelles catégories métiers.', work:'Nettoyage des données, entraînement et comparaison de modèles, livraison de nouvelles versions et migration du pipeline sur Dataiku pour faciliter le réentraînement et le suivi.', scope:'Projet réalisé à la Caisse des Dépôts. Aucun score de performance ni donnée métier confidentielle n’est publié.'},
  {id:'ocr', number:'03', category:'DOCUMENT AI · OCR', title:'Du formulaire numérisé\naux données structurées.', intro:'Traitement de formulaires administratifs et extraction automatique de données.', tags:['Python','PyMuPDF','Tesseract','Pandas'], problem:'Récupérer des informations exploitables à partir de formulaires numérisés, notamment lorsque les pages sont mal orientées.', work:'Extraction de texte, détection et correction de l’orientation des pages, puis récupération de données structurées avec PyMuPDF et OCR.', scope:'Travaux réalisés pendant le stage et l’alternance à la Caisse des Dépôts.'},
];
const groups = [ ['01','Machine Learning','Python, Pandas, NumPy, Scikit-learn','Classification supervisée, clustering, SVM, Naive Bayes, stacking'], ['02','NLP & IA générative','LangChain, Hugging Face, Mistral, FAISS','RAG, embeddings, prompt engineering, spaCy, NLTK'], ['03','Données & pipelines','SQL, Dataiku, PyMuPDF, Tesseract','Préparation des données, OCR, réentraînement et suivi des modèles'], ['04','Deep Learning','TensorFlow, Keras','Deep Learning, séries temporelles et systèmes de recommandation étudiés en master'] ];
const Arrow = () => <span aria-hidden="true">↗</span>;
export default function Home() {return <>
<a className="skip" href="#main">Aller au contenu</a>
<header className="site-header"><a className="monogram" href="#" aria-label="Serigne Bassirou Ndiaye, accueil">SN<span>.</span></a><nav aria-label="Navigation principale"><a href="#projets">Projets</a><a href="#parcours">Parcours</a><a href="#competences">Compétences</a></nav><a className="contact-link" href="#contact">Échangeons <Arrow/></a></header>
<main id="main">
<section className="hero" aria-labelledby="hero-title"><div className="eyebrow"><span className="status-dot"/> DATA SCIENTIST / ML & AI ENGINEER</div><div className="hero-grid"><div><p className="name">Serigne Bassirou NDIAYE</p><h1 id="hero-title">Des données.<br/>Du sens.<br/><span>Des solutions.</span></h1><p className="hero-copy">Machine Learning, NLP et IA générative appliqués aux problématiques métier. Avec un fil conducteur : rendre l’information exploitable.</p><div className="actions"><a className="button primary" href="#projets">Explorer mes projets <span aria-hidden="true">↓</span></a><a className="button secondary" href="/cv-serigne-ndiaye.pdf" download>Mon CV <span aria-hidden="true">↓</span></a></div></div><aside className="focus-panel" aria-label="Domaines de travail"><div className="panel-top"><span>MON TERRAIN D’EXPLORATION</span><span aria-hidden="true">↗</span></div><div className="flow"><div><span>01 / ENTRÉE</span><strong>Documents & données</strong></div><span className="flow-line" aria-hidden="true">↓</span><div><span>02 / MÉTHODES</span><strong>ML · NLP · RAG</strong></div><span className="flow-line" aria-hidden="true">↓</span><div className="flow-end"><span>03 / APPLICATION</span><strong>Information exploitable</strong></div></div><div className="panel-footer"><span>De la recherche documentaire<br/>aux pipelines de classification.</span><span className="tiny-mark" aria-hidden="true">[ AI ]</span></div></aside></div><div className="hero-bottom"><span>EXPÉRIENCE À LA CAISSE DES DÉPÔTS</span><span>MASTER MLSD · UNIVERSITÉ PARIS CITÉ</span><a href="https://github.com/DST-NDIAYE">GitHub <Arrow/></a></div></section>
<section className="about section" id="apropos"><p className="section-label">01 — À PROPOS</p><div><h2>La technique, au service<br/>d’un besoin concret.</h2><p>Mon parcours relie les mathématiques, la science des données et l’ingénierie de solutions IA. À la Caisse des Dépôts, j’ai travaillé sur la classification de courriers, l’extraction de données et la recherche documentaire par IA générative.</p><p>Je recherche un poste en CDI en Data Science ou en ingénierie ML / IA, pour contribuer à des solutions qui répondent à des problématiques métier.</p></div></section>
<section className="section projects" id="projets"><div className="section-heading"><div><p className="section-label">02 — PROJETS SÉLECTIONNÉS</p><h2>L’IA, mise en pratique.</h2></div><p>Trois sujets documentaires.<br/>Des contributions concrètes.</p></div><div className="project-list">{projects.map(p=><article className="project" key={p.id}><div className="project-number">{p.number}<span>/</span></div><div><p className="eyebrow">{p.category}</p><h3>{p.title.split('\n').map((l,i)=><span key={l}>{i>0&&<br/>}{l}</span>)}</h3><p>{p.intro}</p><ul className="tags" aria-label="Technologies">{p.tags.map(t=><li key={t}>{t}</li>)}</ul><details><summary>Lire l’étude de cas <span aria-hidden="true">+</span></summary><div className="case-content"><h4>Le besoin</h4><p>{p.problem}</p><h4>Ma contribution</h4><p>{p.work}</p><h4>Contexte</h4><p>{p.scope}</p></div></details></div><span className="project-arrow" aria-hidden="true">↗</span></article>)}</div><div className="upcoming"><span className="section-label">LA SUITE</span><h3>De nouveaux projets, bientôt.</h3><p>IvoireMaint et des explorations ML / MLOps compléteront cette sélection au fil de leur documentation.</p></div></section>
<section className="section experience" id="parcours"><div><p className="section-label">03 — EXPÉRIENCE</p><h2>Un ancrage<br/>dans les usages.</h2><p className="muted">Caisse des Dépôts<br/>Direction de l’innovation et de la prospective · Paris</p></div><div className="timeline"><article><p className="date">SEPT. 2025 — SEPT. 2026</p><h3>Data Scientist</h3><span className="employment">Alternance</span><p>Évolution d’un pipeline de classification de courriers et migration sur Dataiku. Conception d’un système RAG pour la recherche documentaire.</p><p>Expérimentation de stratégies de prompting pour analyser des dossiers d’appels d’offres et animation d’ateliers sur les LLM.</p></article><article><p className="date">JUIL. 2025 — SEPT. 2025</p><h3>Stagiaire Data Scientist</h3><p>Traitement de formulaires numérisés, correction de l’orientation des pages et extraction de données par OCR. Prise en main du pipeline de classification et formation à Dataiku.</p></article></div></section>
<section className="section" id="competences"><div className="section-heading"><div><p className="section-label">04 — COMPÉTENCES</p><h2>Une stack, des usages.</h2></div><p>Des outils choisis en fonction<br/>du problème à résoudre.</p></div><div className="skills">{groups.map(([n,t,tools,desc])=><article key={n}><span className="skill-number">{n}</span><h3>{t}</h3><p className="tools">{tools}</p><p>{desc}</p></article>)}</div></section>
<section className="section education" id="formation"><div><p className="section-label">05 — FORMATION</p><h2>Des fondations<br/>mathématiques.</h2></div><div><article><span className="date">2024 — 2026</span><h3>Master Informatique · MLSD</h3><p>Machine Learning pour la Science des Données<br/>Université Paris Cité</p></article><article><span className="date">2022 — 2024</span><h3>Licence Mathématiques et Applications</h3><p>Université Paris Cité</p></article><article><span className="date">2019 — 2022</span><h3>Licence Mathématiques et Informatique Appliquées</h3><p>Université Cheikh Anta Diop de Dakar</p></article><div className="certification"><span aria-hidden="true">↗</span><div><h3>6 certifications Dataiku</h3><p>Data Science, Machine Learning, MLOps et IA générative.</p></div></div></div></section>
<section className="contact section" id="contact"><p className="section-label">06 — CONTACT</p><h2>Un sujet Data / IA ?<br/><span>Parlons-en.</span></h2><a className="email" href="mailto:dstndiaye@gmail.com">dstndiaye@gmail.com <Arrow/></a><div className="contact-bottom"><p>À la recherche d’un CDI<br/>Data Scientist · ML & AI Engineer</p><div><a href="https://www.linkedin.com/in/dst-ndiaye/">LinkedIn <Arrow/></a><a href="https://github.com/DST-NDIAYE">GitHub <Arrow/></a><a href="/cv-serigne-ndiaye.pdf" download>Télécharger mon CV ↓</a></div></div></section>
</main><footer><span>© 2026 Serigne Bassirou NDIAYE</span><a href="#">Retour en haut ↑</a></footer></>}
